### ISSUE TITLE
application crash

### ISSUE THREAD

**Issue by michielveen** [bengmathew/tpaw#5] opened 2023-12-02 17:19 UTC
crash report 77eb50a9f6504c8da9408055e59f9c0e

Not 100% sure how I did it but I think it was something like this:
1. I went back to a tab where I had used TPAW planner some time ago.
2. I refreshed the page and it came back as a white page with nothing on it.
3. I refreshed again and I got the start screen, after clicking create your plan got the crash report page

I am not sure about 1. I might have gone to an open tab with some other stuff on and then I keyed in tpaw (autocomplete will give me your site)

hmmm while still on the same tab I keyed in https://tpawplanner.com/, clicked on create your plan and again a crash
2bcdcd10e62a44e8a8ea00647cc9f648 

If I start in a new tab everything works. I am using Chrome.

After I started TPAW in a new tab I went back to the tab with the 2 crashes, I was not able to generate a third crash, it is now working fine.

Good luck,
Michiel

**Comment by bengmathew** [comment] 2023-12-03 19:24
Thanks for reporting the crashes, along with a detailed description of what led up to it. That was very helpful context.

The first crash was due to a network issue—the WebAssembly code couldn't compile because of a network issue. Looks like this WebAssembly event has happened once before, on Sep 21. I believe this is a transient issue, but we'll keep an eye on it.

The crash report for the second error did not include a stack trace, so it's hard to tell what's going on.
We've seen about ten about these types of errors in the last 3 months. We'd love to know what's causing it. But to get to the bottom of this, we will need a way to reproduce it. We tried reproducing the crashes, but have not able to yet. For now, we'll just have to keep an eye on it. Let us know if it happens again, or if you're able to reproduce it.

Interesting that both crashes happened in quick succession on the same tab. They're probably related somehow, but we don't have enough information to connect them.

Closing the issue for now. Please reopen if it happens again.

**Comment by michielveen** [comment] 2023-12-21 08:53
dafb6e14838e402fa62016e9b1dbfc7d

1 chrome browser going to home URL  
2 click on create your plan resulting in a blank screen (url = https://tpawplanner.com/plan)
3 refresh browser on url stap 2, resulting in crash report dafb6e14838e402fa62016e9b1dbfc7d
4 refresh same tab crash report 0f7e40fb6c0a46d4b342da2f2b0f4249
5 refresh same tab and the application is working

**Comment by bengmathew** [comment] 2023-12-23 17:27
Both these crashes are exactly the same as the last time around, so it's clearly the same issue.  I think we can confirm now that the crash before and after the reload are connected and that this sequence of multiple crashes is reproducible. It’s interesting that two separate crashes across reloads are connected (and then a second reload fixes it).

We still can’t reproduce it on our end. We do however have some guesses for what might be going on. We will put some code around these guesses and see how that goes.

Thanks for the update. It was really helpful to learn that it happened again. Please let us know whenever it happens—it's helpful for us to know how frequent this issue is.

Reopening the issue.

**Comment by michielveen** [comment] 2024-10-07 07:28
I don't think I had any crashes in 2024, I think you can close this.

**Comment by bengmathew** [comment] 2024-10-07 16:12
Thanks for following up. Glad to hear that it did not happen again. There are also some bigger architectural changes coming shortly (to support more complex modeling for duration matching) that is going to replace the section of the code that we suspect caused this. 

I'll close this.

**Closed as completed** 2024-10-07 16:13 UTC
